-- phpMyAdmin SQL Dump
-- version 4.4.15.5
-- http://www.phpmyadmin.net
--
-- Host: localhost:3306
-- Generation Time: Dec 13, 2016 at 12:42 PM
-- Server version: 5.5.49-log
-- PHP Version: 7.0.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `g4si`
--

-- --------------------------------------------------------

--
-- Table structure for table `voyage`
--

CREATE TABLE IF NOT EXISTS `voyage` (
  `ID` int(11) NOT NULL,
  `titre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `resum` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `photo1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `section` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `visible` int(11) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `adresse` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `map` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `voyage`
--

INSERT INTO `voyage` (`ID`, `titre`, `resum`, `photo1`, `section`, `visible`, `description`, `adresse`, `map`) VALUES
(1, 'Découvrez de la Mongolie', 'Rencontrez les populations locales pour découvrir de nouveaux univers…', 'mongolie.jpg', 'asie', 3, 'Pourquoi voyager en Mongolie ?\r\n\r\nPartir en Mongolie, c''est avant tout des étendues sans limite. Pas de champ ni de rizière, le climat rendant toute culture intensive impossible, mais de grandioses paysages à perte de vue. Afin de se nourrir, les peuples mongols ont toujours réglé leur mode de vie sur le besoin de leurs troupeaux, partant régulièrement à la recherche de nouveaux pâturages. Si, aujourd''hui, la moitié de la population mongole vit dans les villes, le nomadisme demeure assez logiquement très présent. Ainsi, vous croiserez de nombreuses yourtes, parsemées le long des steppes, au cœur desquelles vous aurez certainement la chance de découvrir la formidable hospitalité locale. Selon les derniers recensements, la Mongolie présente la particularité d''avoir la plus faible densité au monde (1,5 habitants/km²), ce qui explique la préservation exceptionnelle des paysages, des habitats et des traditions. Une destination idéale pour un dépaysement total et une communion avec la nature loin, très loin des sentiers battus.\r\n', '', ''),
(2, 'La Kirghizie en side-car', 'Que vous soyez conducteur du « side-car » ou accompagnant, les fantastiques routes et pistes du Kirghizistan, pays des steppes et des hauts pâturages, n’auront plus aucun secret pour vous.', 'kirghizie.jpg', 'asie', 3, 'Pourquoi voyager au Kirghizistan ?\r\n\r\nIl est des pays dont le nom évoque, au choix, la curiosité, l''inconnu ou encore l''aventure. Pour le Kirghizistan, ce sont ces trois mots qui le décrive le mieux. L’inconnu tout d’abord, car peu facile d''accès enclavé dans les montagnes. La curiosité ensuite, car les habitants y vivent à cheval, et son semi-nomade, mais aussi car ce pays est loin, très loin de nos habitudes occidentales. L’aventure enfin, car un voyage au Kirghizistan est une véritable épopée, une découverte à la recherche d''un monde différent, abrupt, auquel on se confronte avec modestie et humilité. Le Kirghizistan n''est pas une destination pour les citadins et les adeptes du « tout servi sur un plateau ». La rigueur des hauts plateaux, la majesté des montagnes et le rythme de la vie nomade demandent une approche volontaire, décidée et non pas subite. Cependant, à celui qui sait s''en approcher, le pays offrira des souvenirs comme nul part ailleurs, ceux du voyage d''une vie, d''une odyssée hors du commun, qui marque une existence pour toujours.\r\n', '', ''),
(3, 'Découvrez le Pérou ! ', 'À la poursuite des Mondes perdus du Pérou pour les grands et les petits à partir de 8 ans, du pays des Incas à la mystérieuse jungle amazonienne…', 'perou.jpg', 'amerique', 1, 'Pourquoi voyager au Pérou ? \r\n\r\nBienvenue en ces pages Voyage au Pérou. Le Pérou offre un large éventail de découvertes au voyageur, parole de voyageur aguerri : vous ne serez pas déçu ! Incontournables des incontournables de votre voyage : la découverte des vestiges de la civilisation Inca, Machu Pichu en tête… Vous trouverez au Pérou la plus grande et la plus belle concentration de sites archéologiques de l’ère précolombienne. Ici chaque pierre a son importance et chaque couleur sa signification. Mais les vestiges incas ne sont pas le seul atout du pays. Lors de votre séjour au Pérou, les beautés de la nature sauront vous surprendre ! Vous aurez l’occasion de vous prélasser devant de sublimes couchers de soleil sur l’océan Pacifique, de vous balader dans un des canyons les plus profonds du monde, d’observer une faune et une flore étonnantes. La biodiversité péruvienne, l’une des plus riches au monde, est protégée grâce aux nombreux parcs nationaux qui occupent pas moins de 14% du territoire péruvien… Et enfin, lors de votre voyage au Pérou, vous tomberez sans aucun doute sous le charme du peuple péruvien, étonnant mélange entre l’héritage des civilisations précolombiennes et les traditions apportées par la colonisation espagnole...\r\n', '', ''),
(4, 'Découvrir et voyager au Costa Rica..', 'Profitez des grands classiques du Costa Rica et du Panama, si proches et pourtant si opposés. Ce voyage permettra aux grands voyageurs de réaliser un circuit complet entre les deux pays, succombant aux paysages hauts en couleurs!', 'costa.jpg', 'amerique', 1, 'Pourquoi voyager au Costa Rica ?\r\n\r\nBienvenue en ces pages voyage au Costa Rica. Vous êtes prêt(e) à mettre le pied dans l’un des plus beaux joyaux écologiques au monde… Celle que Christophe Colomb baptisa la côte riche est aujourd’hui considérée comme la Suisse de l’Amérique Centrale. Ici ni favela ni guerre, mais la Pura Vida, la « pure vie » ou le bon esprit affiché en toutes circonstances… Les Costariciens (Ticos pour les initiés), sont de bonne humeur constante ! Le Costa Rica, c’est aussi la première nation du monde à avoir supprimé son armée. Le pays est régulièrement classé en tête des pays où il fait bon vivre et il se distingue par son modèle de développement donnant la priorité à l''éducation, à la santé et à la protection de l''environnement. Passionné de nature, vous serez ici au paradis… Le Costa Rica est un pays pionnier de l’éco-tourisme, et sa biodiversité est d’une extrême richesse. Des espèces uniques évoluent dans quelques-uns des 33 parcs nationaux et réserves du pays : pas moins d’un quart du sol costaricien est situé en zone protégée ! Un voyage au Costa Rica, c’est découvrir un paradis sauvage où les gens sont heureux, que demander de mieux ?\r\n', '', ''),
(5, 'Islande : la magie du grand Nord', 'Qui n’a jamais rêvé d’un séjour dans la neige sous les aurores boréales ? ', 'islandejpg', 'europe', 2, 'Pourquoi voyager en Islande ?\r\n\r\nVous envisagez de partir en Islande ? Le pays des elfes et des fées vous fait rêver ? C''est parti ! L''Islande est la destination nature par excellence. Une ode à notre terre, où aurores boréales en hiver et soleil de minuit l’été se font concurrence. C’est également la rare occasion de vivre un véritable dépaysement sans partir trop loin.\r\n', '', ''),
(6, 'Randonnées en raquette de neige en Suède', 'Nous vous proposons un séjour authentique en raquettes dans cet univers naturel.', 'suede.jpg', 'europe', 2, 'Pourquoi voyager en Suède ? \r\n\r\nTerre magique au bord de la mer Baltique, aussi froide que peu peuplée. Car la Suède, c’est aussi ça : un territoire où le nombre de pins dépasse celui des habitants, un territoire méconnu des touristes, aucunement endommagé par les folies de l’homme. Entre étendues d’eau, chiens de traineau, immenses forêts de pins, troupeaux de rennes, aurores boréales, et châteaux royaux, la Suède offre un spectacle éblouissant de beauté et de naturel, notamment en Laponie. Voilà le côté pile. Côté face, vous retrouverez la Suède urbaine, moderne et vivante, précurseur du design et grande reine de la musique. Vous visiterez les quartiers animés de l’archipel de Stockholm et ses 24 000 îles et îlots. Vous vous laisserez porter par une atmosphère toute particulière, propre aux pays du Nord… et peut-être même vous laisserez-vous aller à vous prendre pour un Viking sur l’île de Björkö !\r\n', '', ''),
(7, 'La Crète inconnue et ses facettes ', 'Un thème environnemental abordé dans un voyage aux nombreuses facettes anthropocentriques, à la découverte des plus beaux mais aussi des facettes inconnues du relief crétois. ', 'crete.jpg', 'europe', 2, 'Pourquoi voyager en Crète ?\r\n\r\nSituée au large de la Grèce et à seulement quelques heures d''avion de Paris, l’île de Crète est une destination mythique, paradisiaque et idéale pour ceux qui recherchent un cadre différent, au confluent des cultures, dans un décor où le magnifique alterne avec le sauvage. Vivre un séjour en Crête, c''est se plonger dans une histoire millénaire, où les Dieux de l''Antiquité côtoient une civilisation légendaire, comme en témoignent les riches ruines de Cnossos, non loin de la splendide ville d''Heraklion, les remparts de Rethymon ou l''incroyable forteresse de Frangokastello. Cependant, la Crète n''est pas que vestiges et Histoire : c''est aussi un paradis où les amoureux de la nature seront aux anges, avec les Gorges de Samaria, la presqu''ile d''Elafonissi ou encore le plateau du Lassithi. Enfin, voyager en Crète, c''est également aller à la rencontre d''un peuple hospitalier et chaleureux, à la découverte de petits villages côtiers où il fait bon vivre au rythme des saisons et au gré du soleil. Vous adorerez flâner à Agios Nikolaos, Loutro ou Matala, ou découvrir les régions moins touristiques comme la plaine de la Messara.\r\n', '', ''),
(8, 'Les saveurs de la Sicile', 'Prenez le temps de découvrir la Sicile. Île majestueuse et mystérieuse, tant par son histoire, sa culture que sa géographie,  vous permettra de profiter de ses innombrables richesses.', 'sicile.jpg', 'europe', 2, 'Pourquoi voyager en Sicile ?\r\n\r\nAutant le dire dès le début : partir en Sicile, ce n''est pas partir en Italie. Si, officiellement, la première fait bel et bien partie de la seconde (en tant que région indépendante), dans les faits, la vérité est toute autre. En effet, la Sicile est une terre à part, dotée de sa propre histoire, de son propre patrimoine – aussi varié qu’impressionnant – et de sa beauté propre, enchanteresse, envoûtante. La plus grande île de la Méditerranée baigne dans une atmosphère d''échanges, de partages et de traditions. S''il n’est pas aisé d''en percer les secrets du premier coup, la Sicile se dévoile peu à peu et captive alors l''âme du voyageur. La beauté idyllique des paysages (les Îles Eoliennes, Cefalù ou l''Etna), le caractère aussi abrupt qu''attachant de ses habitants, le charme tranquille de ses villes (Palerme, Taormine, Catane), tout cela associé à un patrimoine qui semble aussi vieux que le monde font de la Sicile une destination à part et immanquable dans une vie !\r\n', '', ''),
(9, 'Terre de feu et lézards de lave aux Galápagos', 'Ce programme de découverte et aventure, spécialement conçu pour voyager en famille, vous permettra d’explorer trois grandes régions. ', 'galapagos.jpg', 'amerique', 1, 'Pourquoi voyager aux Iles Galápagos?\r\n\r\nIl existe, dans l''Océan Pacifique, un archipel de 41 îles où la vie s''est développée pendant des millénaires sans être perturbée. Propriété de l’Équateur, ces 41 îles constituent un eldorado recherché par les amateurs de nature, de décors idylliques et d''une destination décalée : les Galápagos ! Un voyage dans cette région du monde est l''expérience d''une vie entière. Loin de tout, l''archipel des Galápagos recèle monts et merveilles qui séduisent chaque année un nombre croissant de touristes désireux, eux aussi, de parcourir des plages de sable blanc et d''apercevoir une faune absolument unique sur l''une des nombreuses îles. Dès lors, si vous avez toujours rêvé de marcher sur les traces de Darwin, si vous êtes un aficionado de l’ornithologie sous toutes ses formes et si vous aimez par-dessus tout vous extasier devant des décors magnifiques, le tout dans l''atmosphère si spéciale des îles du Pacifique alors n''allez pas chercher plus loin : les Galápagos doivent être votre prochaine destination !\r\n', '', ''),
(10, 'Les visages du Cap Vert', 'Découvrez la diversité des îles du Cabo Verde !', 'cap.jpg', 'afrique', 4, 'Pourquoi voyager au Cap Vert ?\r\n\r\nSitué au large du Sénégal, en plein cœur de l''océan Atlantique, le Cap Vert est un archipel de métissage au carrefour de l''Europe, de l''Afrique et de l''Amérique. Choisir un voyage au Cap Vert, c''est avant tout découvrir l''empreinte puissante des traditions portugaises, les plages désertes et les volcans du pays dans un décor tropical et authentique. Sur l''île principale, São Tiago, l''on trouve la capitale de l''archipel, Praia, ainsi que la ville de Tarrafal, réputée pour ses plages. Pour les voyageurs avides d''exotisme, l''île désertique de Sal devrait en surprendre plus d''un avec ses plages sauvages aux eaux turquoise bordées de sable blanc. Ceux qui rêvent de faire la fête dans un endroit paradisiaque iront à Mindelo, sur São Vicente, quand les amateurs de randonnées partiront pour Santo Antão avec ses paysages montagneux et sa végétation luxuriante. Un voyage au Cap Vert sous le signe du farniente, des découvertes culturelles et des superbes paysages !\r\n', '', ''),
(11, 'Le meilleur du Malawi', 'Du bush Zambien aux eaux transparentes du lac Malawi en passant par le parc national de Liwonde, aventurez-vous dans le warm heart of africa tout en douceur !', 'malawi.jpg', 'afrique', 4, 'Pourquoi voyager au Malawi ? \r\n\r\nSitué en Afrique Australie, le Malawi est un pays peu connu par les voyageurs, encore assez à l''écart des voyages touristiques habituels, ce qui en fait une destination d''exception, qui attire essentiellement des voyageurs amateurs de grands espaces et de nature. Si vous vous demandez en effet « Mais pourquoi aller au Malawi ? », les réponses sont nombreuses car ce pays est riche de diversité et ne saurait être résumé si simplement. C''est une destination à privilégier si vous aimez les safaris et les aventures dans des parcs nationaux de légende tels que celui de Liwonde, où se trouvent éléphants, hippopotames et crocodiles, ou encore celui de Nyika (le plus grand du pays) où les léopards règnent en maître. Le Malawi est également une terre de contrastes, biosphère de l''UNESCO depuis 2000, où le troisième plus grand lac du continent, le lac Malawi, côtoie les incroyables montagnes du massif Mulanje et son plus haut sommet, le Pic Sapitwa. Randonneurs et amateurs d''activités nautiques ou de randonnés trouveront ici matière à s''exercer, s''amuser, à pratiquer, que vous soyez attirés par l''eau ou par la terre ! Un voyage au Malawi est souvent une expérience unique, décalée, à forte résonance historique, puisque que le Grand Rift traverse le pays du Nord au Sud, là-même où l''Humanité a fait (littéralement) ses premiers pas... comme vous ferez les vôtres !\r\n', '', ''),
(12, 'Escapade néo-zélandaise', 'De Christchurch à Queenstown, découvrez les plus beaux paysages du centre de l’Ile du Sud, avec ses lacs et ses montagnes. Puis, continuez votre voyage entre Wellington et Auckland, ou vous serez éblouis par ses paysages volcaniques et géothermiques.', 'zelande.jpg', 'oceanie', 5, 'Pourquoi voyager en Nouvelle Zélande ?\r\nBienvenue en ces pages de voyage en Nouvelle Zélande. Vous atteindrez en ce lointain pays un mélange harmonieux de lacs, de paysages montagneux et volcaniques et de végétation tropicale… La Nouvelle Zélande, isolée au milieu de l''océan, se situe à mi-chemin entre le pôle Sud et l''équateur. Si elle est petite en superficie (la moitié de la France), elle n''en est pas moins dotée d''une nature exceptionnelle d''une grande diversité. Les amoureux de la nature arrivent ici au paradis. Un paradis qui se gagne : il vous faudra de longues heures d''avion pour vous y rendre et on comptera 10 à 12 heures de décalage horaire selon la saison… Mais cette terre que les premiers Maoris baptisèrent Aotearoa, la terre du long nuage blanc, vaut vraiment le déplacement : une nature abondante et diversifiée, des paysages grandioses, des activités de plein air… Le tout à portée de voyageur : un des avantages de cette destination est la taille réduite du pays, qui rend toutes ses beautés accessibles dès le premier séjour en Nouvelle-Zélande. Votre soif de grands espaces et votre envie de calme et de sérénité seront étanchées…\r\n\r\n', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `voyage`
--
ALTER TABLE `voyage`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `voyage`
--
ALTER TABLE `voyage`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=13;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
